# Generated by Django 5.0.1 on 2024-02-02 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiuser',
            name='role',
            field=models.CharField(choices=[('MODERATOR', 'Moderator'), ('STUDENT', 'Student'), ('TEACHER', 'Teacher')], max_length=50),
        ),
    ]
